### ISSUE TITLE
Table of contents doesn't handle big lists well and goes over the footer

### ISSUE THREAD

**Issue by paulocfjunior** [traefik/mkdocs-material#10]
## Description

When there are too many titles or subtitles, the Table of Contents, on the right side of the page, doesn't fit the items properly and doesn't allow scrolling.

### Expected behavior

The table of contents can be scrolled to allow a click on any link, and it should not go over the footer.

### Actual behavior

The table of contents is not scrollable and goes over the footer.
This can be reproduced by duplicating content in some MD file until the Table of Contents become bigger than the screen.

<img width="1254" alt="Screen Shot 2021-01-06 at 10 31 56" src="https://user-images.githubusercontent.com/38889364/103774636-a94a1900-500b-11eb-9cde-ac9ccf716b57.png">

**Comment by traefiker** [comment]
Closed by #16.
