### ISSUE TITLE
Sidebar menu doesn't scroll

### ISSUE THREAD

**Issue by paulocfjunior** [traefik/mkdocs-material#11]
## Description

When there are many items in the sidebar menu, and we scroll the page, the last items are not visible because they go under the footer component.

### Expected behavior

If the menu is too long for the screen, it scrolls and it's possible to comfortably access the last item on it.

### Actual behavior

If the menu is too long for the screen, the last items are not visible or accessible.

https://user-images.githubusercontent.com/38889364/103779198-2a0c1380-5012-11eb-859c-940f5a88576b.mp4

**Comment by traefiker** [comment]
Closed by #16.
