### ISSUE TITLE
Sidebars not scrollable: Need to scroll the entire page to see bottom of them

### ISSUE THREAD

**Issue by paulocfjunior** [traefik/mkdocs-material#34]
## Description

The sidebars don't have scrolls so if they are bigger than the screen, we need to scroll the entire page to see its end.

### Expected behavior

We can scroll to see any item on the sidebars without needing to scroll the page.

### Actual behavior

We need to scroll the entire page to see the last items of big sidebar menus.

https://user-images.githubusercontent.com/38889364/104638517-076aa200-5685-11eb-89e2-a204f9c4dc25.mp4

**Comment by traefiker** [comment]
Closed by #40.
