### ISSUE TITLE
Table of contents marks previous items in a confusing way

### ISSUE THREAD

**Issue by paulocfjunior** [traefik/mkdocs-material#6]
## Description

When there are many items on the sidebar, and we scroll down, it marks previous items in bold, but not the current one. It's a weird UX, we could improve it by making the previous items lighter and the only current one bold.

### Suggested behavior

<img width="1182" alt="Screen Shot 2021-01-05 at 16 54 52" src="https://user-images.githubusercontent.com/38889364/103692598-bff26080-4f76-11eb-8b69-db21a50fda35.png">

### Actual behavior

<img width="1190" alt="Screen Shot 2021-01-05 at 16 08 51" src="https://user-images.githubusercontent.com/38889364/103688484-9f270c80-4f70-11eb-87e2-a56c24424aab.png">

**Comment by matthieuh** [comment]
That seems in effect a great UX improvements!

**Comment by paulocfjunior** [comment]
Regarding the last item in the table of contents, it's still not marked as active if it's shorter than the page height. Adding an empty space to the bottom of the page seems to solve, but it's a weird UX, so I prefer not to do that, and solving this with another approach seems to be too costly, so we can do it in another [issue](https://github.com/traefik/mkdocs-material/issues/39).
